services:
  - type: web
    name: api-livros
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
